### ISSUE TITLE
en ver clickers:  que vengan filtrados por “id_channel”

### ISSUE THREAD

**Issue by oscar7aylor** [arcaderlife/clicker-www#6]

**Comment by Ch1Ch0** [comment]
Filtra por idchannel solo que se repite si tiene mas de un usuario, se podria poner que nada mas salga un idchannel y que en la columna de usuarios salgan separados por una coma los usuarios.

**Comment by Ch1Ch0** [comment]
Adjunto screenshot

![screen shot 2017-07-16 at 12 19 23 pm](https://user-images.githubusercontent.com/3820057/28250274-88d45344-6a21-11e7-846d-2f8a73a4e20d.png)

**Comment by oscar7aylor** [comment]
mae si eso funcionaria tuanis

**Comment by Ch1Ch0** [comment]
fixed
