### ISSUE TITLE
en ver clickers: habilitar capacidad de modificar asignaciones de clickers.

### ISSUE THREAD

**Issue by oscar7aylor** [arcaderlife/clicker-www#7]

**Comment by oscar7aylor** [comment]
en ver clickers: habilitar capacidad de modificar asignaciones de clickers. Por ejemplo, queria que el usuario de pruebas no tuviera clickers asignados pero no encontré forma de hacerlo. to en ver clickers: habilitar capacidad de modificar asignaciones de clickers.

**Comment by Ch1Ch0** [comment]
Se habilitó la función de desasignar un clicker de un usuario y un dato de un clicker.
