### ISSUE TITLE
en agregar clicker: que el campo Id Channel siga siendo editable pero venga prellenado. 

### ISSUE THREAD

**Issue by oscar7aylor** [arcaderlife/clicker-www#8]
Por ejemplo, si el último clicker que se agregó fue el "clicker_3" entonces que este campo venga ya con "clicker_4" como sugerencia.

**Comment by oscar7aylor** [comment]
Esta cargando prellenado pero sin el numero al final.

La idea de tenerlo prellenado es que a veces no se va a saber como va la cuenta de clickers, ahorita solo tenemos 2 o 3 pero si llegamos a tener algunos mas entonces va a ser difícil acordarse por donde va la cuenta. 

Entonces si actualmente el clicker mas alto registrado es digamos clicker_420 entonces el campo debería venir prellenado con clicker_421 para que al admin le quede fácil mantener la cuenta en orden.

**Comment by Ch1Ch0** [comment]
Ah ok, en todas.
