### ISSUE TITLE
en ver datos:  que muestre a que clicker esta asignado el dato, no solo a que usuario. 

### ISSUE THREAD

**Issue by oscar7aylor** [arcaderlife/clicker-www#9]
Por que a veces hay varios datos que se llaman igual (entrada).

**Comment by Ch1Ch0** [comment]
De hecho muestra el nombre del clicker al que esta asignado. Podría decir mas bien "Asignado a Clicker"

**Comment by oscar7aylor** [comment]
Mae si lleguele

**Comment by Ch1Ch0** [comment]
fixed
